import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { type Document } from "@shared/schema";
import { Loader2 } from "lucide-react";

interface VersionModalProps {
  isOpen: boolean;
  onClose: () => void;
  document: Document;
}

export default function VersionModal({ isOpen, onClose, document }: VersionModalProps) {
  const [newDemand, setNewDemand] = useState("");
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const createVersionMutation = useMutation({
    mutationFn: async (demand: string) => {
      const response = await fetch(`/api/documents/${document.id}/versions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title: document.title,
          type: document.type,
          content: "", // Will be generated by AI
          originalDemand: demand,
        }),
      });
      
      if (!response.ok) {
        throw new Error("Falha ao criar nova versão");
      }
      
      return response.json();
    },
    onSuccess: (newVersion) => {
      toast({
        title: "Nova versão criada",
        description: `Versão ${newVersion.version} do documento "${document.title}" foi criada com sucesso.`,
      });
      
      // Invalidate queries to refresh the document list and versions
      queryClient.invalidateQueries({ queryKey: ["/api/documents"] });
      queryClient.invalidateQueries({ queryKey: ["/api/documents", document.id, "versions"] });
      
      // Trigger download of the new version
      window.location.href = `/api/documents/${newVersion.id}/download`;
      
      onClose();
      setNewDemand("");
    },
    onError: (error) => {
      toast({
        title: "Erro ao criar versão",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDemand.trim()) {
      toast({
        title: "Campo obrigatório",
        description: "Por favor, descreva as mudanças ou novos requisitos.",
        variant: "destructive",
      });
      return;
    }
    createVersionMutation.mutate(newDemand);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Nova Versão do Documento</DialogTitle>
          <DialogDescription>
            Crie uma nova versão de "{document.title}" com requisitos atualizados ou modificações.
          </DialogDescription>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="original-demand">Documento Original:</Label>
            <div className="p-3 bg-gray-50 rounded-md text-sm text-gray-600 max-h-32 overflow-y-auto">
              {document.originalDemand}
            </div>
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="new-demand">Novos Requisitos ou Modificações:</Label>
            <Textarea
              id="new-demand"
              value={newDemand}
              onChange={(e) => setNewDemand(e.target.value)}
              placeholder="Descreva as mudanças, novos requisitos ou melhorias que devem ser aplicadas nesta nova versão..."
              className="min-h-[120px]"
              disabled={createVersionMutation.isPending}
            />
          </div>
          
          <div className="flex justify-end space-x-2 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={onClose}
              disabled={createVersionMutation.isPending}
            >
              Cancelar
            </Button>
            <Button
              type="submit"
              disabled={createVersionMutation.isPending || !newDemand.trim()}
            >
              {createVersionMutation.isPending && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              Gerar Nova Versão
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}